// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type RefreshToken struct {
	ID         int64      `json:"id"`
	UserID     int64      `json:"user_id"`
	TokenHash  string     `json:"token_hash"`
	DeviceInfo []byte     `json:"device_info"`
	ExpiresAt  time.Time  `json:"expires_at"`
	CreatedAt  time.Time  `json:"created_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
}

type User struct {
	ID                int64      `json:"id"`
	Email             string     `json:"email"`
	Username          string     `json:"username"`
	PasswordHash      string     `json:"password_hash"`
	EmailVerified     bool       `json:"email_verified"`
	Active            bool       `json:"active"`
	Role              string     `json:"role"`
	PrivacySettings   []byte     `json:"privacy_settings"`
	LastLoginAt       *time.Time `json:"last_login_at"`
	PasswordChangedAt time.Time  `json:"password_changed_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

type UserProfile struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Phone     string    `json:"phone"`
	AvatarUrl string    `json:"avatar_url"`
	Bio       string    `json:"bio"`
	Timezone  string    `json:"timezone"`
	Locale    string    `json:"locale"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
