// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo []byte             `json:"device_info"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	EmailVerified     pgtype.Bool        `json:"email_verified"`
	Active            pgtype.Bool        `json:"active"`
	Role              pgtype.Text        `json:"role"`
	PrivacySettings   []byte             `json:"privacy_settings"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	FirstName pgtype.Text        `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	Phone     pgtype.Text        `json:"phone"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	Bio       pgtype.Text        `json:"bio"`
	Timezone  pgtype.Text        `json:"timezone"`
	Locale    pgtype.Text        `json:"locale"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
