// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	ActivateUser(ctx context.Context, id int64) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id int64) error
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserWithProfile(ctx context.Context, id int64) (GetUserWithProfileRow, error)
	MarkEmailVerified(ctx context.Context, id int64) error
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPrivacySettings(ctx context.Context, arg UpdateUserPrivacySettingsParams) error
}

var _ Querier = (*Queries)(nil)
