services:
  whoami-db:
    image: postgres:alpine
    container_name: whoami-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - whoami-db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  whoami-redis:
    image: redis:7-alpine
    container_name: whoami-redis
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  whoami:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: whoami
    depends_on:
      whoami-db:
        condition: service_healthy
      whoami-redis:
        condition: service_healthy
    environment:
      HTTP_SERVER_ADDRESS: ${HTTP_SERVER_ADDRESS}
      HTTP_PORT: ${HTTP_PORT}
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_SOURCE: ${DB_SOURCE}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
      TOKEN_SYMMETRIC_KEY: ${TOKEN_SYMMETRIC_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
volumes:
  whoami-db:
