services:
  whoami-db:
    image: postgres:alpine
    container_name: whoami-db
    environment:
      POSTGRES_USER: ${}
      POSTGRES_PASSWORD: ${}
      POSTGRES_DB: ${}
      PGPORT: ${}
    volumes:
      - whoami-db:/var/lib/postgresql/data
    ports:
      - "${}:${}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${} -d ${}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  whoami-redis:
    image: redis:7-alpine
    container_name: whoami-redis
    command: --port ${}
    ports:
      - "${}:${}"
    restart: unless-stopped
  whoami:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: whoami
    depends_on:
      whoami-db:
        condition: service_healthy
      whoami-redis:
        condition: service_healthy
volumes:
  whoami-db:
