services:
  whoami-db:
    image: postgres:alpine
    container_name: whoami-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - whoami-db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  whoami-redis:
    image: redis:7-alpine
    container_name: whoami-redis
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - whoami-redis:/data
    restart: unless-stopped
  whoami-migrate:
    build:
      context: ../
      dockerfile: deployment/migrate/Dockerfile
    depends_on:
      whoami-db:
        condition: service_healthy
    volumes:
      - ../internal/db/migrations:/migrations
    environment:
      MIGRATE_DB_URL_MIGRATE: "${DB_URL_MIGRATE}"
    command: ["-path", "/migrations", "-database", "${DB_URL_MIGRATE}", "up"]
  whoami:
    build:
      context: ../
      dockerfile: deployment/whoami/Dockerfile
    container_name: whoami
    depends_on:
      whoami-db:
        condition: service_healthy
      whoami-redis:
        condition: service_healthy
      whoami-migrate:
        condition: service_completed_successfully

    environment:
      HTTP_SERVER_ADDRESS: ${HTTP_SERVER_ADDRESS}
      HTTP_PORT: ${HTTP_PORT}
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_SOURCE: ${DB_SOURCE}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
      TOKEN_SYMMETRIC_KEY: ${TOKEN_SYMMETRIC_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_OAUTH_REDIRECT_URL: ${GOOGLE_OAUTH_REDIRECT_URL}
      GITHUB_OAUTH_CLIENT_ID: ${GITHUB_OAUTH_CLIENT_ID}
      GITHUB_OAUTH_CLIENT_SECRET: ${GITHUB_OAUTH_CLIENT_SECRET}
      GITHUB_OAUTH_REDIRECT_URL: ${GITHUB_OAUTH_REDIRECT_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ENABLE_TLS: ${ENABLE_TLS}
      TLS_CERT_FILE: ${TLS_CERT_FILE}
      TLS_KEY_FILE: ${TLS_KEY_FILE}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - ../deployment/certs:/certs:ro
      - whoami-exports:/app/exports
volumes:
  whoami-db:
  whoami-redis:
  whoami-exports:
